//api 2 Returns a specific todo based on the todo ID
GET http://localhost:3000/todos/3/
###

//api 3 Create a todo in the todo table,

POST http://localhost:3000/todos/ 
Content-Type: application/json

{
  "id": 10,
  "todo": "Finalize event theme",
  "priority": "LOW",
  "status": "TO DO"
}

###


//api 4

PUT http://localhost:3000/todos/3/
Content-Type: application/json

{
  "status": "DONE"
}

//api 5 Deletes a todo from the todo table based on the todo ID

DELETE http://localhost:3000/todos/3/
###
